const LOGGED_IN_SUCCESSFUL = "LOGGED_IN_SUCCESSFUL"
const LOGGED_IN_FAILED = "LOGGED_IN_FAILED"
const LOGGED_IN_REQUEST = "LOGGED_IN_REQUEST"
const RESTORE_LOGIN_USER_SESSION = "RESTORE_LOGIN_USER_SESSION"
const UNSUCCESSFULLY_LOGIN_USER_SESSION = "UNSUCCESSFULLY_LOGIN_USER_SESSION"
const LOGOUT = "LOGOUT"


export {
    LOGGED_IN_SUCCESSFUL,
    LOGGED_IN_FAILED,
    LOGGED_IN_REQUEST,
    RESTORE_LOGIN_USER_SESSION,
    UNSUCCESSFULLY_LOGIN_USER_SESSION,
    LOGOUT
}